name: 'crypto_stream_lakehouse'
version: '1.0.0'
config-version: 2

profile: 'crypto_stream_lakehouse'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  crypto_stream_lakehouse:
    staging:
      +materialized: view
      +schema: silver
    marts:
      +materialized: table
      +schema: gold